name: Test Docker Image
on:
  push:
    branches: ['*']
jobs:
  build:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
      pg: [12, 11, 10, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.4]
    name: 🐘 PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t pgxn-tools-test .
      - run: docker run -it --rm --mount "type=bind,src=$(pwd)/test,dst=/repo" pgxn-tools-test sh -c 'cd /repo && pg-start ${{ matrix.pg }} && pg-build-test'
